-- Additive Agent schema: seven new tables, no existing-table alterations.
-- Generated from short_drama.domain.agent; select the intended database first.
-- Use scripts/agent_migration.py --apply for safe table-level reentry.

CREATE TABLE agent_conversations (
	id BIGINT UNSIGNED NOT NULL,
	owner_user_id BIGINT UNSIGNED NOT NULL,
	project_id BIGINT UNSIGNED NOT NULL,
	episode_id BIGINT UNSIGNED NOT NULL,
	title VARCHAR(120) NOT NULL DEFAULT '新对话',
	status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'active',
	row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
	next_message_seq BIGINT UNSIGNED NOT NULL DEFAULT 1,
	next_event_seq BIGINT UNSIGNED NOT NULL DEFAULT 1,
	fixed_requirements JSON NOT NULL DEFAULT (JSON_OBJECT()),
	create_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
	create_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_conversations_owner FOREIGN KEY(owner_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_conversations_project FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_conversations_episode FOREIGN KEY(episode_id) REFERENCES episodes (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_conversation_create UNIQUE (owner_user_id, create_key),
	CONSTRAINT ck_agent_conversations_status CHECK (status IN ('active','archived')),
	CONSTRAINT ck_agent_conversations_numbers CHECK (row_version > 0 AND next_message_seq > 0 AND next_event_seq > 0),
	CONSTRAINT ck_agent_conversations_requirements CHECK (JSON_TYPE(fixed_requirements) = 'OBJECT'),
	CONSTRAINT ck_agent_conversations_title CHECK (CHAR_LENGTH(TRIM(title)) > 0),
	CONSTRAINT ck_agent_conversations_create_pair CHECK ((create_key IS NULL) = (create_hash IS NULL)),
	CONSTRAINT ck_agent_conversations_create_hash CHECK (create_key IS NULL OR (CHAR_LENGTH(create_key) = 64 AND CHAR_LENGTH(create_hash) = 64)),
	CONSTRAINT ck_agent_conversations_time CHECK (updated_at >= created_at)
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_agent_conversations_owner_episode ON agent_conversations (owner_user_id, episode_id, updated_at, id);

CREATE INDEX idx_agent_conversations_project ON agent_conversations (project_id, owner_user_id, id);

CREATE TABLE agent_messages (
	id BIGINT UNSIGNED NOT NULL,
	conversation_id BIGINT UNSIGNED NOT NULL,
	seq BIGINT UNSIGNED NOT NULL,
	`role` VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL,
	content MEDIUMTEXT NOT NULL DEFAULT (''),
	`references` JSON NOT NULL DEFAULT (JSON_ARRAY()),
	artifacts JSON NOT NULL DEFAULT (JSON_ARRAY()),
	idempotency_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
	request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_messages_conversation FOREIGN KEY(conversation_id) REFERENCES agent_conversations (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_messages_seq UNIQUE (conversation_id, seq),
	CONSTRAINT uk_agent_messages_request UNIQUE (conversation_id, idempotency_key),
	CONSTRAINT uk_agent_messages_parent UNIQUE (id, conversation_id),
	CONSTRAINT ck_agent_messages_seq CHECK (seq > 0),
	CONSTRAINT ck_agent_messages_role CHECK (role IN ('user','assistant')),
	CONSTRAINT ck_agent_messages_arrays CHECK (JSON_TYPE(`references`) = 'ARRAY' AND JSON_TYPE(artifacts) = 'ARRAY'),
	CONSTRAINT ck_agent_messages_content_size CHECK (OCTET_LENGTH(content) <= 1048576),
	CONSTRAINT ck_agent_messages_nonempty CHECK (CHAR_LENGTH(TRIM(content)) > 0 OR JSON_LENGTH(`references`) > 0 OR JSON_LENGTH(artifacts) > 0),
	CONSTRAINT ck_agent_messages_request_pair CHECK ((idempotency_key IS NULL) = (request_hash IS NULL)),
	CONSTRAINT ck_agent_messages_request_hash CHECK (idempotency_key IS NULL OR (role = 'user' AND CHAR_LENGTH(idempotency_key) = 64 AND CHAR_LENGTH(request_hash) = 64))
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE agent_runs (
	id BIGINT UNSIGNED NOT NULL,
	conversation_id BIGINT UNSIGNED NOT NULL,
	trigger_message_id BIGINT UNSIGNED NOT NULL,
	initiated_by BIGINT UNSIGNED NOT NULL,
	model_config_id BIGINT UNSIGNED NOT NULL,
	status VARCHAR(24) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'queued',
	phase VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'model',
	active_conversation_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status IN ('queued','running','waiting_generation','waiting_review') THEN conversation_id ELSE NULL END) STORED,
	row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
	checkpoint_schema_version INTEGER UNSIGNED NOT NULL DEFAULT 1,
	checkpoint JSON NOT NULL DEFAULT (JSON_OBJECT()),
	config_snapshot JSON NOT NULL DEFAULT (JSON_OBJECT()),
	budget JSON NOT NULL DEFAULT (JSON_OBJECT()),
	`usage` JSON NOT NULL DEFAULT (JSON_OBJECT()),
	message_status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'pending',
	message_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
	next_run_at DATETIME(6),
	lease_token CHAR(32) CHARACTER SET ascii COLLATE ascii_bin,
	lease_until DATETIME(6),
	cancel_requested INTEGER UNSIGNED NOT NULL DEFAULT 0,
	error JSON,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	started_at DATETIME(6),
	finished_at DATETIME(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_runs_conversation FOREIGN KEY(conversation_id) REFERENCES agent_conversations (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_runs_trigger_message FOREIGN KEY(trigger_message_id, conversation_id) REFERENCES agent_messages (id, conversation_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_runs_initiator FOREIGN KEY(initiated_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_runs_model FOREIGN KEY(model_config_id) REFERENCES ai_model_configs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_runs_trigger UNIQUE (trigger_message_id),
	CONSTRAINT uk_agent_runs_active_conversation UNIQUE (active_conversation_id),
	CONSTRAINT uk_agent_runs_parent UNIQUE (id, conversation_id),
	CONSTRAINT ck_agent_runs_status CHECK (status IN ('queued','running','waiting_generation','waiting_review','succeeded','failed','cancelled')),
	CONSTRAINT ck_agent_runs_phase CHECK (phase IN ('model','tools','wait')),
	CONSTRAINT ck_agent_runs_message_status CHECK (message_status IN ('pending','publishing','published','idle')),
	CONSTRAINT ck_agent_runs_versions CHECK (row_version > 0 AND message_version > 0 AND checkpoint_schema_version > 0),
	CONSTRAINT ck_agent_runs_cancel CHECK (cancel_requested IN (0,1)),
	CONSTRAINT ck_agent_runs_lease_pair CHECK ((lease_token IS NULL) = (lease_until IS NULL)),
	CONSTRAINT ck_agent_runs_objects CHECK (JSON_TYPE(checkpoint) = 'OBJECT' AND JSON_TYPE(config_snapshot) = 'OBJECT' AND JSON_TYPE(budget) = 'OBJECT' AND JSON_TYPE(`usage`) = 'OBJECT'),
	CONSTRAINT ck_agent_runs_error CHECK (error IS NULL OR JSON_TYPE(error) = 'OBJECT'),
	CONSTRAINT ck_agent_runs_terminal_time CHECK ((status IN ('succeeded','failed','cancelled')) = (finished_at IS NOT NULL)),
	CONSTRAINT ck_agent_runs_time CHECK (updated_at >= created_at AND (started_at IS NULL OR started_at >= created_at) AND (finished_at IS NULL OR finished_at >= created_at) AND (started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at))
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_agent_runs_history ON agent_runs (conversation_id, created_at, id);

CREATE INDEX idx_agent_runs_lease ON agent_runs (lease_until, status, id);

CREATE INDEX idx_agent_runs_schedule ON agent_runs (message_status, next_run_at, id);

CREATE TABLE agent_events (
	id BIGINT UNSIGNED NOT NULL,
	conversation_id BIGINT UNSIGNED NOT NULL,
	run_id BIGINT UNSIGNED,
	seq BIGINT UNSIGNED NOT NULL,
	event_type VARCHAR(64) COLLATE utf8mb4_0900_bin NOT NULL,
	payload JSON NOT NULL DEFAULT (JSON_OBJECT()),
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_events_conversation FOREIGN KEY(conversation_id) REFERENCES agent_conversations (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_events_run FOREIGN KEY(run_id, conversation_id) REFERENCES agent_runs (id, conversation_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_events_seq UNIQUE (conversation_id, seq),
	CONSTRAINT ck_agent_events_required CHECK (seq > 0 AND CHAR_LENGTH(TRIM(event_type)) > 0),
	CONSTRAINT ck_agent_events_payload CHECK (JSON_TYPE(payload) = 'OBJECT')
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_agent_events_run ON agent_events (run_id, seq);

CREATE TABLE agent_turns (
	id BIGINT UNSIGNED NOT NULL,
	run_id BIGINT UNSIGNED NOT NULL,
	turn_no INTEGER UNSIGNED NOT NULL,
	status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'prepared',
	request_messages JSON NOT NULL DEFAULT (JSON_ARRAY()),
	response JSON,
	`usage` JSON NOT NULL DEFAULT (JSON_OBJECT()),
	provider_response_id VARCHAR(255) COLLATE utf8mb4_0900_bin,
	error JSON,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	started_at DATETIME(6),
	finished_at DATETIME(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_turns_run FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_turns_number UNIQUE (run_id, turn_no),
	CONSTRAINT uk_agent_turns_parent UNIQUE (id, run_id),
	CONSTRAINT ck_agent_turns_number CHECK (turn_no > 0),
	CONSTRAINT ck_agent_turns_status CHECK (status IN ('prepared','sent','succeeded','failed','unknown')),
	CONSTRAINT ck_agent_turns_payload CHECK (JSON_TYPE(request_messages) = 'ARRAY' AND JSON_TYPE(`usage`) = 'OBJECT'),
	CONSTRAINT ck_agent_turns_result CHECK ((response IS NULL OR JSON_TYPE(response) = 'OBJECT') AND (error IS NULL OR JSON_TYPE(error) = 'OBJECT')),
	CONSTRAINT ck_agent_turns_time CHECK (updated_at >= created_at AND (started_at IS NULL OR started_at >= created_at) AND (finished_at IS NULL OR finished_at >= created_at) AND (started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at))
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE agent_tool_calls (
	id BIGINT UNSIGNED NOT NULL,
	run_id BIGINT UNSIGNED NOT NULL,
	turn_id BIGINT UNSIGNED NOT NULL,
	call_index INTEGER UNSIGNED NOT NULL,
	provider_call_id VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL,
	tool_name VARCHAR(80) COLLATE utf8mb4_0900_bin NOT NULL,
	arguments JSON NOT NULL DEFAULT (JSON_OBJECT()),
	arguments_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
	idempotency_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
	status VARCHAR(24) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'prepared',
	result JSON,
	generation_task_id BIGINT UNSIGNED,
	review_payload JSON,
	review_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
	review_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
	review_decision VARCHAR(16) COLLATE utf8mb4_0900_bin,
	reviewed_by BIGINT UNSIGNED,
	reviewed_at DATETIME(6),
	error JSON,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_tool_calls_run FOREIGN KEY(run_id) REFERENCES agent_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_tool_calls_turn FOREIGN KEY(turn_id, run_id) REFERENCES agent_turns (id, run_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_tool_calls_generation FOREIGN KEY(generation_task_id) REFERENCES async_tasks (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_tool_calls_reviewer FOREIGN KEY(reviewed_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_tool_calls_provider UNIQUE (turn_id, provider_call_id),
	CONSTRAINT uk_agent_tool_calls_order UNIQUE (turn_id, call_index),
	CONSTRAINT uk_agent_tool_calls_request UNIQUE (idempotency_key),
	CONSTRAINT uk_agent_tool_calls_generation UNIQUE (generation_task_id),
	CONSTRAINT ck_agent_tool_calls_numbers CHECK (call_index > 0 AND review_version > 0),
	CONSTRAINT ck_agent_tool_calls_required CHECK (CHAR_LENGTH(TRIM(provider_call_id)) > 0 AND CHAR_LENGTH(TRIM(tool_name)) > 0 AND CHAR_LENGTH(arguments_hash) = 64 AND CHAR_LENGTH(idempotency_key) = 64),
	CONSTRAINT ck_agent_tool_calls_status CHECK (status IN ('prepared','waiting_review','ready','running','waiting_generation','succeeded','failed','rejected','cancelled')),
	CONSTRAINT ck_agent_tool_calls_objects CHECK (JSON_TYPE(arguments) = 'OBJECT' AND (result IS NULL OR JSON_TYPE(result) = 'OBJECT') AND (error IS NULL OR JSON_TYPE(error) = 'OBJECT')),
	CONSTRAINT ck_agent_tool_calls_review_pair CHECK ((review_payload IS NULL) = (review_hash IS NULL)),
	CONSTRAINT ck_agent_tool_calls_review_payload CHECK (review_payload IS NULL OR (JSON_TYPE(review_payload) = 'OBJECT' AND CHAR_LENGTH(review_hash) = 64)),
	CONSTRAINT ck_agent_tool_calls_review_decision CHECK (review_decision IS NULL OR review_decision IN ('approved','rejected')),
	CONSTRAINT ck_agent_tool_calls_review_actor CHECK ((review_decision IS NULL AND reviewed_by IS NULL AND reviewed_at IS NULL) OR (review_decision IS NOT NULL AND review_payload IS NOT NULL AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)),
	CONSTRAINT ck_agent_tool_calls_review_pending CHECK (status <> 'waiting_review' OR (review_payload IS NOT NULL AND review_decision IS NULL)),
	CONSTRAINT ck_agent_tool_calls_time CHECK (updated_at >= created_at AND (reviewed_at IS NULL OR reviewed_at >= created_at))
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_agent_tool_calls_run_status ON agent_tool_calls (run_id, status, id);

CREATE TABLE agent_artifacts (
	id BIGINT UNSIGNED NOT NULL,
	project_id BIGINT UNSIGNED NOT NULL,
	episode_id BIGINT UNSIGNED NOT NULL,
	tool_call_id BIGINT UNSIGNED NOT NULL,
	result_index INTEGER UNSIGNED NOT NULL,
	kind VARCHAR(32) COLLATE utf8mb4_0900_bin NOT NULL,
	status VARCHAR(16) COLLATE utf8mb4_0900_bin NOT NULL DEFAULT 'ready',
	row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
	source_snapshot JSON NOT NULL DEFAULT (JSON_OBJECT()),
	source_content MEDIUMTEXT,
	metadata_json JSON NOT NULL DEFAULT (JSON_OBJECT()),
	proposed_patch JSON,
	script_id BIGINT UNSIGNED,
	parent_script_id BIGINT UNSIGNED,
	generation_task_id BIGINT UNSIGNED,
	media_asset_id BIGINT UNSIGNED,
	media_id BIGINT UNSIGNED,
	target_asset_id BIGINT UNSIGNED,
	target_shot_id BIGINT UNSIGNED,
	created_by BIGINT UNSIGNED NOT NULL,
	applied_by BIGINT UNSIGNED,
	applied_at DATETIME(6),
	apply_receipt JSON,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	CONSTRAINT fk_agent_artifacts_project FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_episode FOREIGN KEY(episode_id) REFERENCES episodes (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_tool FOREIGN KEY(tool_call_id) REFERENCES agent_tool_calls (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_script FOREIGN KEY(script_id) REFERENCES episode_scripts (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_parent_script FOREIGN KEY(parent_script_id) REFERENCES episode_scripts (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_generation FOREIGN KEY(generation_task_id) REFERENCES async_tasks (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_media_asset FOREIGN KEY(media_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_media FOREIGN KEY(media_id) REFERENCES media_files (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_asset FOREIGN KEY(target_asset_id) REFERENCES assets (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_shot FOREIGN KEY(target_shot_id) REFERENCES shot_scripts (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_creator FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_agent_artifacts_adopter FOREIGN KEY(applied_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT uk_agent_artifacts_result UNIQUE (tool_call_id, result_index),
	CONSTRAINT uk_agent_artifacts_script UNIQUE (script_id),
	CONSTRAINT ck_agent_artifacts_kind CHECK (kind IN ('novel_proposal','text_proposal','script_candidate','asset_patch','shot_patch','extraction_candidate','storyboard_candidate','image_candidate','video_candidate')),
	CONSTRAINT ck_agent_artifacts_status CHECK (status IN ('ready','applied','rejected','archived')),
	CONSTRAINT ck_agent_artifacts_numbers CHECK (row_version > 0 AND result_index > 0),
	CONSTRAINT ck_agent_artifacts_objects CHECK (JSON_TYPE(source_snapshot) = 'OBJECT' AND JSON_TYPE(metadata_json) = 'OBJECT' AND (proposed_patch IS NULL OR JSON_TYPE(proposed_patch) = 'OBJECT') AND (apply_receipt IS NULL OR JSON_TYPE(apply_receipt) = 'OBJECT')),
	CONSTRAINT ck_agent_artifacts_source_size CHECK (source_content IS NULL OR OCTET_LENGTH(source_content) <= 1048576),
	CONSTRAINT ck_agent_artifacts_text_proposal CHECK (kind NOT IN ('novel_proposal','text_proposal') OR (source_content IS NOT NULL AND CHAR_LENGTH(TRIM(source_content)) > 0)),
	CONSTRAINT ck_agent_artifacts_script_candidate CHECK (kind <> 'script_candidate' OR script_id IS NOT NULL),
	CONSTRAINT ck_agent_artifacts_asset_patch CHECK (kind <> 'asset_patch' OR (target_asset_id IS NOT NULL AND proposed_patch IS NOT NULL)),
	CONSTRAINT ck_agent_artifacts_shot_patch CHECK (kind <> 'shot_patch' OR (target_shot_id IS NOT NULL AND proposed_patch IS NOT NULL)),
	CONSTRAINT ck_agent_artifacts_adoption CHECK ((status = 'applied' AND applied_by IS NOT NULL AND applied_at IS NOT NULL AND apply_receipt IS NOT NULL) OR (status <> 'applied' AND applied_by IS NULL AND applied_at IS NULL AND apply_receipt IS NULL)),
	CONSTRAINT ck_agent_artifacts_time CHECK (updated_at >= created_at AND (applied_at IS NULL OR applied_at >= created_at))
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_agent_artifacts_episode ON agent_artifacts (episode_id, kind, status, created_at, id);

CREATE INDEX idx_agent_artifacts_generation ON agent_artifacts (generation_task_id, id);
