-- Additive upgrade, use the Python runner to resume partial application.
ALTER TABLE media_files ADD COLUMN video_metadata JSON NULL COMMENT 'ffprobe actual video metadata', ADD CONSTRAINT ck_media_video_metadata CHECK (video_metadata IS NULL OR JSON_TYPE(video_metadata) = 'OBJECT');

CREATE TABLE `episode_assemblies` (
  `id` BIGINT UNSIGNED NOT NULL,
  `episode_id` BIGINT UNSIGNED NOT NULL,
  `aspect` VARCHAR(8) NOT NULL,
  `resolution` VARCHAR(16) NOT NULL DEFAULT '720p',
  `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `current_media_id` BIGINT UNSIGNED NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ck_assemblies_aspect` CHECK (aspect IN ('16:9','9:16')),
  CONSTRAINT `ck_assemblies_resolution` CHECK (resolution IN ('720p','1080p')),
  CONSTRAINT `ck_assemblies_version` CHECK (row_version > 0),
  CONSTRAINT `fk_assemblies_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_assemblies_media` FOREIGN KEY (`current_media_id`) REFERENCES `media_files` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE KEY `uk_assemblies_episode` (`episode_id`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='分集成片草稿与当前采用成片';

CREATE TABLE `episode_assembly_clips` (
  `id` BIGINT UNSIGNED NOT NULL,
  `assembly_id` BIGINT UNSIGNED NOT NULL,
  `shot_id` BIGINT UNSIGNED NOT NULL,
  `media_id` BIGINT UNSIGNED NULL,
  `position` INT UNSIGNED NOT NULL,
  `included` INT UNSIGNED NOT NULL DEFAULT 1,
  `muted` INT UNSIGNED NOT NULL DEFAULT 0,
  `trim_in_ms` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `trim_out_ms` BIGINT UNSIGNED NULL,
  `source_context_hash` CHAR(64) CHARACTER SET ascii NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ck_assembly_clips_flags` CHECK (included IN (0,1) AND muted IN (0,1)),
  CONSTRAINT `ck_assembly_clips_position` CHECK (position > 0),
  CONSTRAINT `ck_assembly_clips_trim` CHECK (trim_out_ms IS NULL OR trim_out_ms > trim_in_ms),
  CONSTRAINT `fk_assembly_clips_assembly` FOREIGN KEY (`assembly_id`) REFERENCES `episode_assemblies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_assembly_clips_media` FOREIGN KEY (`media_id`) REFERENCES `media_files` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_assembly_clips_shot` FOREIGN KEY (`shot_id`) REFERENCES `shot_scripts` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE KEY `uk_assembly_clips_position` (`assembly_id`, `position`),
  UNIQUE KEY `uk_assembly_clips_shot` (`assembly_id`, `shot_id`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='成片片段顺序与非破坏性剪辑设置';

CREATE TABLE `episode_render_jobs` (
  `id` BIGINT UNSIGNED NOT NULL,
  `assembly_id` BIGINT UNSIGNED NOT NULL,
  `kind` VARCHAR(16) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'queued',
  `stage` VARCHAR(24) NOT NULL DEFAULT 'queued',
  `snapshot` JSON NOT NULL,
  `context_hash` CHAR(64) CHARACTER SET ascii NOT NULL,
  `idempotency_key` VARCHAR(128) COLLATE utf8mb4_0900_bin NOT NULL,
  `request_hash` CHAR(64) CHARACTER SET ascii NOT NULL,
  `progress` INT UNSIGNED NOT NULL DEFAULT 0,
  `attempts` INT UNSIGNED NOT NULL DEFAULT 0,
  `message_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `next_run_at` DATETIME(6) NOT NULL,
  `lease_token` CHAR(32) CHARACTER SET ascii NULL,
  `locked_until` DATETIME(6) NULL,
  `cancel_requested` INT UNSIGNED NOT NULL DEFAULT 0,
  `output_media_id` BIGINT UNSIGNED NULL,
  `manifest` JSON NULL,
  `error` JSON NULL,
  `retry_of_id` BIGINT UNSIGNED NULL COMMENT '原任务ID，由服务层验证同成片归属',
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `finished_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ck_render_jobs_error` CHECK (error IS NULL OR JSON_TYPE(error) = 'OBJECT'),
  CONSTRAINT `ck_render_jobs_kind` CHECK (kind IN ('probe','export')),
  CONSTRAINT `ck_render_jobs_manifest` CHECK (manifest IS NULL OR JSON_TYPE(manifest) = 'OBJECT'),
  CONSTRAINT `ck_render_jobs_progress` CHECK (progress <= 100 AND cancel_requested IN (0,1)),
  CONSTRAINT `ck_render_jobs_snapshot` CHECK (JSON_TYPE(snapshot) = 'OBJECT'),
  CONSTRAINT `ck_render_jobs_status` CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
  CONSTRAINT `ck_render_jobs_version` CHECK (message_version > 0),
  CONSTRAINT `fk_render_jobs_assembly` FOREIGN KEY (`assembly_id`) REFERENCES `episode_assemblies` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_render_jobs_media` FOREIGN KEY (`output_media_id`) REFERENCES `media_files` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE KEY `uk_render_jobs_request` (`assembly_id`, `kind`, `idempotency_key`),
  KEY `idx_render_jobs_history` (`assembly_id`, `kind`, `created_at`, `id`),
  KEY `idx_render_jobs_schedule` (`status`, `next_run_at`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='本地媒体探测与成片合成任务，不调用AI供应商';
