-- 首次完整画布创建的私人准备状态；用 canvas_migration.py --apply 安全重入。
CREATE TABLE canvas_creation_attempts (
	user_id BIGINT UNSIGNED NOT NULL, 
	idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, 
	operation_kind VARCHAR(32) NOT NULL, 
	request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, 
	request_json JSON NOT NULL, 
	source_key VARCHAR(64) COLLATE utf8mb4_0900_bin NOT NULL, 
	target_project_id BIGINT UNSIGNED, 
	status VARCHAR(16) NOT NULL, 
	expires_at DATETIME(6) NOT NULL, 
	result_json JSON, 
	id BIGINT UNSIGNED NOT NULL, 
	created_at DATETIME(6) NOT NULL, 
	updated_at DATETIME(6) NOT NULL, 
	created_by BIGINT UNSIGNED NOT NULL, 
	updated_by BIGINT UNSIGNED NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uk_canvas_creation_identity UNIQUE (user_id, idempotency_key), 
	CONSTRAINT uk_canvas_creation_source_key UNIQUE (user_id, source_key), 
	CONSTRAINT uk_canvas_creation_owner UNIQUE (id, user_id), 
	CONSTRAINT ck_canvas_creation_destination CHECK ((operation_kind = 'canvas.workspace.create' AND target_project_id IS NULL) OR (operation_kind = 'canvas.create' AND target_project_id IS NOT NULL)), 
	CONSTRAINT ck_canvas_creation_result CHECK ((status = 'pending' AND result_json IS NULL) OR (status = 'ready' AND result_json IS NOT NULL)), 
	CONSTRAINT ck_canvas_creation_identity CHECK (CHAR_LENGTH(request_hash) = 64 AND CHAR_LENGTH(source_key) > 0), 
	CONSTRAINT fk_canvas_creation_attempts_user_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_attempts_target_project_id FOREIGN KEY(target_project_id) REFERENCES projects (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_attempts_created_by FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_attempts_updated_by FOREIGN KEY(updated_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX idx_canvas_creation_expiry ON canvas_creation_attempts (status, expires_at);

CREATE TABLE canvas_creation_resources (
	attempt_id BIGINT UNSIGNED NOT NULL, 
	user_id BIGINT UNSIGNED NOT NULL, 
	source_resource_id BIGINT UNSIGNED NOT NULL, 
	source_media_id BIGINT UNSIGNED, 
	source_binary_id BIGINT UNSIGNED, 
	snapshot_json JSON NOT NULL, 
	target_resource_id BIGINT UNSIGNED NOT NULL, 
	storage_locator VARCHAR(700) COLLATE utf8mb4_0900_bin NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	copied_at DATETIME(6), 
	released_at DATETIME(6), 
	id BIGINT UNSIGNED NOT NULL, 
	created_at DATETIME(6) NOT NULL, 
	updated_at DATETIME(6) NOT NULL, 
	created_by BIGINT UNSIGNED NOT NULL, 
	updated_by BIGINT UNSIGNED NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT fk_canvas_creation_resource_owner FOREIGN KEY(attempt_id, user_id) REFERENCES canvas_creation_attempts (id, user_id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT uk_canvas_creation_resource UNIQUE (attempt_id, source_resource_id), 
	CONSTRAINT uk_canvas_creation_target UNIQUE (target_resource_id), 
	CONSTRAINT uk_canvas_creation_locator UNIQUE (storage_locator), 
	CONSTRAINT ck_canvas_creation_source_pin CHECK ((released_at IS NULL AND ((source_media_id IS NULL) <> (source_binary_id IS NULL))) OR (released_at IS NOT NULL AND source_media_id IS NULL AND source_binary_id IS NULL)), 
	CONSTRAINT ck_canvas_creation_resource_state CHECK ((status = 'pending' AND copied_at IS NULL) OR (status IN ('copied','attached') AND copied_at IS NOT NULL AND released_at IS NOT NULL)), 
	CONSTRAINT ck_canvas_creation_resource_ids CHECK (source_resource_id > 0 AND target_resource_id > 0), 
	CONSTRAINT fk_canvas_creation_resources_source_media_id FOREIGN KEY(source_media_id) REFERENCES media_files (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_resources_source_binary_id FOREIGN KEY(source_binary_id) REFERENCES canvas_binary_resources (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_resources_created_by FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT, 
	CONSTRAINT fk_canvas_creation_resources_updated_by FOREIGN KEY(updated_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci;
